version: '3'
services:
  api-gateway:
    build:
      context: ../src/services/api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../key/server.cert:/usr/src/app/server.cert
      - ../key/server.key:/usr/src/app/server.key
    command: npm run start
    networks:
      - app_network
  
  user-service:
    build:
      context: ../src/services/user-service
    ports:
      - "3001:3000"
      - "50051:50051"
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network
  
  official-artist-service:
    build:
      context: ../src/services/official-artist-service
    ports:
      - "3002:3000"
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network
  
  music-service:
    build:
      context: ../src/services/music-service
    ports:
      - "3003:3000"
      - "50053:50053"
    depends_on:
      - user-service
      - official-artist-service
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network
  
  history-service:
    build:
      context: ../src/services/history-service
    ports:
      - "3004:3000"
      - "50054:50054"
    depends_on:
      - music-service
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network
  
  love-service:
    build:
      context: ../src/services/love-service
    ports:
      - "3005:3000"
      - "50055:50055"
    depends_on:
      - music-service
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network

  follow-service:
    build:
      context: ../src/services/follow-service
    ports:
      - "3006:3000"
    depends_on:
      - user-service
      - official-artist-service
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network

  playlist-service:
    build:
      context: ../src/services/playlist-service
    ports:
      - "3007:3000"
    depends_on:
      - music-service
      - follow-service
      - love-service
      - history-service
      - user-service
      - official-artist-service
    env_file:
      - ../.env
    volumes:
      - ../key/key.json:/usr/src/app/key.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run start
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
