version: '3'
services:
  api-gateway:
    build:
      context: ../src/services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service

  user-service:
    build:
      context: ../src/services/user-service
    ports:
      - "3001:3001"
    depends_on:
      - any-service

  any-service:
    build:
      context: ../src/services/any-service
    ports:
      - "3002:3002"